

//select all users 

GET http://localhost:4444/user-api/userss
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZGlkZHkuY29tIiwiaWF0IjoxNzczMzAyNDgwLCJleHAiOjE3NzMzMDYwODB9.ePrG4GM806gHElT_3GAcQFGjtM9OKtFGAUeLaSTtgss; Path=/; HttpOnly; SameSite=Lax
//read user by specific 

### 
GET http://localhost:4444/user-api/user

###
GET http://localhost:4444/user-api/users/kai cenat

###new user
POST http://localhost:4444/user-api/users
Content-Type: application/json


  {
    "username":"kai cenat",
    "password":"diddy123",
    "email":"test@diddy.com",
    "age":20
  }

###user login

POST http://localhost:4444/user-api/auth
Content-Type: application/json

{
  "email":"test@diddy.com",
  "password":"diddy123"
}





###update user
PUT http://localhost:4444/user-api/users/69aa8c7b2f539f491ec580bc
Content-Type: application/json

{
    "username":"hasrithh",
    "password":"nunnu4",
    "email": "diddy@epen.com",
    "age": 12
}
###
PUT http://localhost:4444/user-api/users/cart/prd-id/69abb7236074f357e48a9d03

###
DELETE http://localhost:4444/user-api/users/69abf9930e503690f824bea8

//dont't have any body



//delete and get request don't support body
//so that these two requets can send data through endpoint



//only post and put request have the body
//so they should send the data as body of the request



###
GET http://localhost:4444/product-api/product
###
GET http://localhost:4444/product-api/product/69ab07169ce3fe1d3b5911dc
###
POST http://localhost:4444/product-api/product
Content-Type: application/json

{
      "productID":10112,
     "productName":"Nothing 4a",
      "price": 35000,
      "brand": "Nothing"
}


###
PUT   http://localhost:4444/product-api/product/69ab07169ce3fe1d3b5911dc
Content-Type: application/json

 {
      "productID":10112,
     "productName":"Nothing 4a",
      "price": 30000,
      "brand": "Nothing"
}



###
DELETE http://localhost:4444/product-api/product/69ab07169ce3fe1d3b5911dc



